# Generated by Django 2.1.13 on 2019-11-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_iamge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='iamge',
            new_name='image',
        ),
    ]
